### PR TITLE
Add entry_points to setup.py

### PR DESCRIPTION
**Pull request by delijati**
See #74

### CODE REVIEW

**Comment by delijati** [comment]
I signed it!

**Comment by delijati** [comment]
I signed it!

**Comment by fahhem** [comment]
Hey, how would you like to be mentioned in the `CONTRIBUTORS` file? I have your name from your profile, but no email. You don't have to have one in there if you don't want

**Comment by fahhem** [comment]
https://github.com/google/python-adb/pull/85

**Pull request merged**
