### PR TITLE
Fixed TypeError in TcpHandle and sign_pythonrsa

### PR DESCRIPTION
**Pull request by YSunLIN**
See #86 

In Python3, using `str` as the type of _buf causes `TypeError: Can't convert 'bytes' object to str implicitly` in the newest commit 0b15f4fc69c8b9ed87a82964fd6d2eed8d637f21 with python-rsa.
```python
  File ".\adb.zip\__main__.py", line 210, in <module>
  File ".\adb.zip\__main__.py", line 206, in main
  File ".\adb.zip\adb\common_cli.py", line 149, in StartCli
  File ".\adb.zip\adb\adb_commands.py", line 138, in ConnectDevice
  File ".\adb.zip\adb\adb_commands.py", line 169, in _Connect
  File ".\adb.zip\adb\adb_protocol.py", line 320, in Connect
  File ".\adb.zip\adb\sign_pythonrsa.py", line 69, in Sign
  File "E:\Python\Python3\lib\site-packages\rsa\pkcs1.py", line 272, in sign
    hash = _hash(message, hash)
  File "E:\Python\Python3\lib\site-packages\rsa\pkcs1.py", line 346, in _hash
    hasher.update(message)
  File ".\adb.zip\adb\sign_pythonrsa.py", line 29, in update
TypeError: Can't convert 'bytes' object to str implicitly
```

And it can be fixed below:
```python
   # hashing algo for this.
   class _Accum(object):
     def __init__(self):
 -     self._buf = ''
 +     self._buf = b''
     def update(self, msg):
       self._buf += msg
     def digest(self):
       return self._buf
```

And thanks to @Myonium, the TypeError in TcpHandle can also be resolved.

@fahhem I don't know why this PR cannot be accepted. If you guys don't want to merge this branch, just close it.

### CODE REVIEW

**Comment by fahhem** [comment]
Hmm, this seems to cause problems with the USB handle. It seems the TCPHandle needs to convert to bytes in the right place, because the signing libraries should only see binary data, not unicode.

**Comment by YSunLIN** [comment]
@fahhem I opened the issue #86 and then made a pull request #89 to fix the problem. 
I also merged the @Myonium's TcpHandle solution with which you agreed.
However, you merged #97 and ignored this PR until now.
I don't know if it is discrimination or not.

**Comment by YSunLIN** [comment]
Thanks for your prompt reply. And I will continue to contribute to this repo.

**Comment by fahhem** [comment]
Thanks!

**Pull request closed without merging**
