### PR TITLE
AdbCommands.Push(): Added st_mode parameter.

### PR DESCRIPTION
**Pull request by Halastra**
This PR simply exposes the 'st_mode' parameter from FilesyncProtocol.Push() to AdbCommands.Push().
This allows the user to easily upload a file with any desired st_mode.

### CODE REVIEW

**Comment by Halastra** [comment]
I signed it!

**Comment by fahhem** [comment]
Thanks! Want to add yourself to `CONTRIBUTORS`?

**Comment by Halastra** [comment]
Gladly! What do I need to do?

**Comment by fahhem** [comment]
Another PR with your name/email in the CONTRIBUTORS file :)

**Pull request merged**
