### PR TITLE
Python 3 string fixes and additional tests

### PR DESCRIPTION
**Pull request by JeffLIrion**

### CODE REVIEW

**Comment by JeffLIrion** [comment]
I signed it!

**Comment by JeffLIrion** [comment]
Is there anything you need from me for this pull request? I've got a pull request for another Python package (https://github.com/happyleavesaoc/python-firetv) that uses this ADB library and requires these changes for Python 3 compatibility. If you could review this PR and release a new version so that I can update the requirements for firetv, that would be much appreciated!

**Comment by chilicheech** [comment]
Any updates on this? This PR is very useful in for me 😄

**Comment by JeffLIrion** [comment]
I would really appreciate it if you could review this PR. I've got some pull requests that I'd like to submit to other packages -- python-firetv and home-assistant -- that are dependent upon the changes contained in this PR.

**Comment by tuxuser** [comment]
@JeffLIrion usually pull requests dont bump the package version, the maintainer decides when to do so. Maybe you could change that and see if the coverall test accepts it. However, it makes no sense to me why a version bump interferes with code coverage...

Additionally, you could write tests -> higher possibility of it getting accepted.

**Comment by tuxuser** [comment]
I signed it!

**Comment by JeffLIrion** [comment]
I signed it!

**Comment by tuxuser** [comment]
I am very okay with contributing to this project!

**Comment by tuxuser** [comment]
@fahhem Sorry for triggering you, assuming you are quite busy, but it's somewhat urgent. This PR fixes basic py3 compatibility, it would be a great thing to have! Thank you!

**Comment by JeffLIrion** [comment]
I tried to change the email used by @tuxuser in his commits to the email that he used when signing the CLA, but it made a mess of the repository so I reverted to the state before modifying the commit emails. PR https://github.com/google/python-adb/pull/128 is exactly the same, but all the commits are in my name. Sorry for the trouble!

**Comment by fahhem** [comment]
Closing in favor of #128

**Pull request closed without merging**
