### PR TITLE
Fix python3-ism with byte v. str

### PR DESCRIPTION
**Pull request by rustyhowell**
Also make the example in the README a bit more universal.

### CODE REVIEW

**Comment by rustyhowell** [comment]
I signed it!

**Comment by fahhem** [comment]
The tests failed because the % will convert a bytes string to `"b\'<original string>\'"`, which isn't expected (and wrong). If you fix that, I'll merge it ASAP

**Comment by fahhem** [comment]
Ping? Is this worth merging still?

**Comment by rustyhowell** [comment]
I believe this is fixed. You should be able to merge it.

**Comment by fahhem** [comment]
Is this necessary with #128 merged in?

**Comment by tuxuser** [comment]
Can be closed, fix is merged!

**Comment by rustyhowell** [comment]
Probably not anymore. It looks like #128 has my changes in it.

**Pull request closed without merging**
